name: Deploy Allure Report to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install allure-pytest

    - name: Run tests and generate Allure results
      run: |
        pytest --alluredir=allure-results
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
        tar -xzf allure-2.27.0.tgz
        ./allure-2.27.0/bin/allure generate allure-results -o allure-report --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
